### ISSUE TITLE
a comprehension list from a 2-dimensions list

### ISSUE THREAD

**Issue by kerhuon** [celine-m-s/learn-python#1]
double_numbers = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
#create a new list from double_numbers with odd numbers only
# should look like : [1, 3, 5, 7, 9]

**Comment by celine-m-s** [comment]
Added!
See https://github.com/celine-m-s/learn-python/blob/master/list_comprehension.py#L26
